# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 488)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 190, 201, 28))
        self.pushButton.setObjectName("pushButton")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(90, 30, 371, 351))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.DicomBTN = QtWidgets.QPushButton(self.splitter_3)
        self.DicomBTN.setObjectName("DicomBTN")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.IsoSlider = QtWidgets.QSlider(self.splitter)
        self.IsoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.IsoSlider.setObjectName("IsoSlider")
        self.SurfaceBTN = QtWidgets.QPushButton(self.splitter)
        self.SurfaceBTN.setObjectName("SurfaceBTN")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setObjectName("label_2")
        self.TransferSlider = QtWidgets.QSlider(self.splitter_2)
        self.TransferSlider.setOrientation(QtCore.Qt.Horizontal)
        self.TransferSlider.setObjectName("TransferSlider")
        self.RayBTN = QtWidgets.QPushButton(self.splitter_2)
        self.RayBTN.setObjectName("RayBTN")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.DicomBTN.setText(_translate("MainWindow", "Dicom"))
        self.label.setText(_translate("MainWindow", "Surface Rendring"))
        self.SurfaceBTN.setText(_translate("MainWindow", "Surface Rendring"))
        self.label_2.setText(_translate("MainWindow", "Ray Casting"))
        self.RayBTN.setText(_translate("MainWindow", "Raycasting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
